### ISSUE TITLE
Peak summits and annotations

### ISSUE THREAD

**Issue by oriolfornes** [MengQiuchen/cPeaks#5]
Hi, I wanted to congratulate the authors for such a nice and timely resource. Would it be possible/easy for cPeaks to provide the peak summits and annotate the peaks per sample to enable training multi-task CNNs and similar models? Thank you in advance!

**Comment by MengQiuchen** [comment]
Thank you for your message and congratulations. We apologize for the delay in our response and appreciate your interest in our work. 
Regarding your question, for peak summits, we considered the peak summits in cPeaks to be approximate cPeak centers. This can be supported by the experimental evidence shown in Fig. 1e of our paper. For peak annotations, in the current version, we reply on the genetic information and epigenetic experimental data to infer their functions, such as promoters, enhancers and CTCF. We have not added cPeak annotations to our network, as our main goal of neural network is to identify cPeaks across the genome regardless of their specific functions. 
However, we believe that combining cPeaks information along with their annotations can be used to train a model for understanding the sequence patterns associated with different regulatory functions. This can enable a more detailed annotation of the genome.
Thank you again for your kind words and valuable feedback.
